### ISSUE TITLE
Erro no Composer + Phalcon

### ISSUE THREAD

**Issue by lhenriquedeveloper** [iurygdeoliveira/Estudos_de_PHP#12]
Após a instalação do composer e dado inicio ao processo usando o Composer Init, ele exibe esse erro no meu terminal e não cria a pasta Vendor
![erro](https://user-images.githubusercontent.com/62040725/94475946-32002000-01a6-11eb-8ba5-f0cb3dd6d438.jpg)

já estou tentando resolver a um bom tempo mas não consigo!

**Comment by iurygdeoliveira** [comment]
@lhenriquedeveloper, Ele está solicitando a instalação da extensão phalcon na sua máquina local. No windows o procedimento que acredito que resolva o problema é esse

https://phalcon.io/en-us/download/windows

**Comment by iurygdeoliveira** [comment]
@lhenriquedeveloper em minha maquina eu resolvi isso instalando com sudo apt-get install php-phalcon

**Comment by lhenriquedeveloper** [comment]
O João Lucas conseguiu fazer o phalcon e o PHP funcionarem na maquina local Windows sem precisar utilizar dentro do docker. Aparentemente se tratava de algum problema de compatibilidade com as versões sendo necessária utilizar a versão 32 bits do PHP e a x86 equivalente do Phalcon.

Segue em Anexo os Arquivos Utilizados e o Print dele funcionando


![Ae Sim](https://user-images.githubusercontent.com/62040725/94725651-7d473980-0332-11eb-90fb-f8499e80b235.JPG)


[metodo q deu certo.zip](https://github.com/iurygdeoliveira/Estudos_de_PHP/files/5307576/metodo.q.deu.certo.zip)

**Comment by iurygdeoliveira** [comment]
@lhenriquedeveloper maravilha !
