### ISSUE TITLE
EXECUTAR O PHALCON

### ISSUE THREAD

**Issue by EvertonSalesAlencar** [iurygdeoliveira/Estudos_de_PHP#17]
não consegui globalizar o phalcon/devtools e nem executar ele para criar um projeto

![Captura de tela de 2020-09-29 22-29-03](https://user-images.githubusercontent.com/71044680/94633798-c8b30680-02a4-11eb-8343-2a053f93f7d5.png)

**Comment by iurygdeoliveira** [comment]
Executa esse segundo comando aqui é veja se resolve:

chmod ugo+x /usr/bin/phalcon

**Comment by keysoneto** [comment]
Não conseguir executar o comando ln -s $ ( pwd ) / phalcon / usr / bin / phalcon no windows.

**Comment by iurygdeoliveira** [comment]
> Não conseguir executar o comando ln -s $ ( pwd ) / phalcon / usr / bin / phalcon no windows.

@keysoneto esse comando contem um caminho especifico para linux.  Se quiser usar isso no windows, terá que mudar o caminho das pastas, para o especifico no windows.
