### ISSUE TITLE
Como utilizar o phalcon framework na raiz do projeto? (Windows)

### ISSUE THREAD

**Issue by lhenriquedeveloper** [iurygdeoliveira/Estudos_de_PHP#18]
Após a instalação e configuração do composer + phalcon me deparei com um pequeno problema. Ao tentar utilizar o phalcon devtools na pasta raiz do projeto o meu terminal não reconhecia o comando 'phalcon'. Após isso percebi q para utiliza-lo teria que entrar na pasta do devtools e iniciar por lá. O problema é q isso não é nem um pouco produtivo. Nas aulas o professor ensinou a resolver tal problema no linux. Gostaria de saber se tem como no Windows.

**Comment by iurygdeoliveira** [comment]
Vc pode configurar um caminho nas variáveis de ambiente do windows, assim ele ficará global em seu sistema.  Moço, vai aprender linux, não fique só no windows não.
