### ISSUE TITLE
Erro no comando gedit ~/.gitconfig - Windows 10

### ISSUE THREAD

**Issue by carlossaraiva-git** [iurygdeoliveira/Estudos_de_PHP#2]
O comando gedit ~/.gitconfig não está funcionando no windows 10

PS C:\Novos Caminhos> gedit ~/.gitconfig
gedit : O termo 'gedit' não é reconhecido como nome de cmdlet, função, arquivo de script ou programa operável. Verifique a grafia do nome ou, se 
um caminho tiver sido incluído, veja se o caminho está correto e tente novamente.        
No linha:1 caractere:1
+ gedit ~/.gitconfig
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (gedit:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by iurygdeoliveira** [comment]
Olá @carlossaraiva-git tudo bem

O comando gedit é especifico do sistemas linux. É um bloco de notas para linux.
Como está utilizando windows, troque o comando para notepad.exe.

Além disso o sinal ~ é específico para linux, para windows você precisar substituir por c:/users/<usuario da sua maquina>

Você instalou o git bash ?

Me dê um feedback

**Comment by carlossaraiva-git** [comment]
Funcionou o comando notepad.exe,
Além disso, faltava configurar o git bash no settings.json com o comando:
"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"
Resolvido, obrigado!
