### ISSUE TITLE
Opção Sync: Sync now

### ISSUE THREAD

**Issue by carlossaraiva-git** [iurygdeoliveira/Estudos_de_PHP#3]
Existe outra forma de sincronizar que não seja por meio do Ctrl+Shift+P?
Não aparece a opção Sync: sync now na caixa de pesquisa.

**Comment by iurygdeoliveira** [comment]
@carlossaraiva-git tudo bem.

Você instalou a extensão settings sync ??

**Comment by carlossaraiva-git** [comment]
Sim está instalado, verifiquei que precisava ligar (Turn on), pórem ao ligar aparece a mensagem "Error while starting Sync: Unable to sync settings as there are errors/warning in settings file".
Sabe o que poderia ser?

**Comment by iurygdeoliveira** [comment]
Posta o seu arquivo settings.json do vscode aqui, deve ser alguma configuração que está faltando

**Comment by carlossaraiva-git** [comment]
settings.json
{
    "java.home": "C:\\Program Files\\Java\\jdk1.8.0_261",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue"
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"
}

**Comment by iurygdeoliveira** [comment]
@carlossaraiva-git não sei o motivo do seu erro.
