### ISSUE TITLE
Como criar apelidos (aliases) no Cmder (Terminal do Windows)

### ISSUE THREAD

**Issue by lhenriquedeveloper** [iurygdeoliveira/Estudos_de_PHP#4]
link do cmder: https://cmder.net/

**Comment by jlucaso1** [comment]
Para criar um alias é só escrever o comando: alias "nomeDoAlias"="Comando a ser apelidado". Ex: **alias teste=ls**, no momento em que for digitado **teste** no terminal, o comando **ls** será executado. Outra dica é que pode ser usado também argumentos no caso utilizando o "$*". Ex: **alias teste=ls --color $\*** e ao executar ficaria assim **teste yellow**.

**Comment by iurygdeoliveira** [comment]
E ai @lhenriquedeveloper , resolveu ?

**Comment by iurygdeoliveira** [comment]
@lhenriquedeveloper aqui você também encontra informação a respeito

https://github.com/iurygdeoliveira/novos_caminhos/issues/203

**Comment by lhenriquedeveloper** [comment]
Opa professor, consegui sim
