### ISSUE TITLE
Não consigo clonar o repositório do Github

### ISSUE THREAD

**Issue by luanfr91** [iurygdeoliveira/Estudos_de_PHP#5]
Não estou conseguindo fazer a clonagem do repositório do Github para o VS Code no Windows 10.
Instalei o Git pelo executável e digitei os comandos que foi colocado no vídeo 6 no VS Code, mas dizem que os comandos são inválidos.

**Comment by iurygdeoliveira** [comment]
@luanfr91 tudo bem, coloque aqui o print dos resultados, deixe-me ver o que acontece ...

**Comment by luanfr91** [comment]
Fiz o comando do SSH Keygen e ainda sim não consegui importar

![image](https://user-images.githubusercontent.com/71303400/94188313-9312b580-fe7f-11ea-8075-d39309e3f3f4.png)

![image](https://user-images.githubusercontent.com/71303400/94188436-c3f2ea80-fe7f-11ea-9cd6-32e5e003b992.png)

**Comment by iurygdeoliveira** [comment]
@luanfr91 quero fazer um acesso remoto na sua máquina pra ver o que acontece, conhece o programa team viewer ?

https://www.teamviewer.com/pt-br/download/windows/
