### ISSUE TITLE
Sincronização VScode-Github

### ISSUE THREAD

**Issue by EvertonSalesAlencar** [iurygdeoliveira/Estudos_de_PHP#8]
professor acreditei que aquele código faria a sincronização automatica mas não fez. Esse código ( "java.home": "/usr/lib/jvm/jdk-14.0.2",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "todo-tree.tree.showScanModeButton": false,
    "sync.autoDownload": true,
    "sync.autoUpload": true,
    "sync.forceDownload": true,
    "sync.forceUpload": true,
    "sync.quietSync": true,)

deixei em comentario no settings.json add o qual o senhor deixou no github apos ter feito o download.

fui no settings novamente mexi em muitas coisas mas não funcionou, mesmo tendo resetado as configurações do mesmo

![WhatsApp Image 2020-09-25 at 14 39 19](https://user-images.githubusercontent.com/71044680/94299337-e8ad9780-ff3d-11ea-867d-a157987e7d1d.jpeg)

**Comment by iurygdeoliveira** [comment]
@EvertonSalesAlencar preciso acessar sua máquina remotamente, para ver o que acontece

**Comment by EvertonSalesAlencar** [comment]
![WhatsApp Image 2020-09-25 at 15 13 10](https://user-images.githubusercontent.com/71044680/94301939-c4ec5080-ff41-11ea-8690-28c98bd16094.jpeg)

a opção não é clicavel

**Comment by EvertonSalesAlencar** [comment]
lembrei da live do dia 15 onde a jhessik e o bomfim perguntaram sobre a sincronização.

**Comment by EvertonSalesAlencar** [comment]
pelo chromer remote?

**Comment by EvertonSalesAlencar** [comment]
o sync:now é para substituir os comando fetch, merge e push utilizados no terminal para atualizar o repositorio e ver pela pagina do github e pelo vscode?

**Comment by iurygdeoliveira** [comment]
@EvertonSalesAlencar não, o sync now é para sincronizar suas configurações do vscode no github

**Comment by EvertonSalesAlencar** [comment]
ok, quando pode acessar meu not para ver essa situação?

**Comment by iurygdeoliveira** [comment]
@EvertonSalesAlencar no momento da aula terça de noite

**Comment by EvertonSalesAlencar** [comment]
ok
