### ISSUE TITLE
Erro na criação dos Contêineres. 

### ISSUE THREAD

**Issue by lhenriquedeveloper** [iurygdeoliveira/Estudos_de_PHP#9]
Após dar o comando "docker-compose up" para gerar os container, tudo aparentemente ia de acordo até que surgiu o seguinte erro. Após a realização do processo apareceu a seguinte mensagem no terminal: " ERROR: Encountered errors while bringing up the project " e a extensão do docker não exibiu nenhum container, apesar de reconhecer as imagens segue a foto em anexo
![Capturar2](https://user-images.githubusercontent.com/62040725/94305480-9f624580-ff47-11ea-95e1-4cc63c513564.JPG)
![Capturar 1](https://user-images.githubusercontent.com/62040725/94305483-9ffadc00-ff47-11ea-91b7-6baa1d11a13b.JPG)
![Capturar3](https://user-images.githubusercontent.com/62040725/94305484-a0937280-ff47-11ea-94d3-06b47fc17b7e.JPG)

**Comment by iurygdeoliveira** [comment]
Está usando windows @lhenriquedeveloper ??  Se sim, qual programa usou, o docker desktop ?

**Comment by lhenriquedeveloper** [comment]
sim, estou usando o Docker Desktop, andei conversando com outros alunos e alguns relataram alguns pequenos bugs, vou testar usando o cmder em modo administrador, creio que pode ser isso, já q no linux utilizamos o sudo para dar acesso ao usuario root

**Comment by lhenriquedeveloper** [comment]
beleza, ainda não deu certo. Vou reinstalar o docker pra ver se vai

**Comment by lhenriquedeveloper** [comment]
Beleza professor, funcionou, aparentemente eu fiz a instalação da forma errada sem baixar as instancias do wsl que o docker pedia.

**Comment by iurygdeoliveira** [comment]
@lhenriquedeveloper blz !
